
INSERT INTO public.data_brokers (slug, name, website, opt_out_url, opt_out_difficulty, opt_out_time_estimate, requires_id, requires_phone, requires_captcha, instructions, priority, is_active)
VALUES
  ('acxiom', 'Acxiom', 'https://www.acxiom.com', 'https://isapps.acxiom.com/optout/optout.aspx', 'medium', '10 minutes', false, false, true, '1. Visit the Acxiom opt-out form\n2. Fill in your name, email, address, and date of birth\n3. Choose which data products to opt out of (recommend selecting all)\n4. Submit the form\n5. Confirm via email link', 'crucial', true),
  ('epsilon', 'Epsilon', 'https://www.epsilon.com', 'https://www.epsilon.com/us/privacy-policy', 'hard', '15 minutes', false, true, false, '1. Email optout@epsilon.com with subject "Opt-Out Request"\n2. Include your full name, current address, previous addresses (last 5 years), and phone number\n3. State you want to be removed from all marketing databases\n4. Wait 30-60 days for confirmation', 'crucial', true),
  ('lexisnexis', 'LexisNexis', 'https://www.lexisnexis.com', 'https://optout.lexisnexis.com/', 'hard', '20 minutes', true, false, true, '1. Visit the LexisNexis opt-out portal\n2. Fill out the Privacy Request Form\n3. Provide ID verification (driver''s license or passport)\n4. Submit notarized opt-out request via mail if required\n5. Allow 30 days for processing', 'crucial', true),
  ('peekyou', 'PeekYou', 'https://www.peekyou.com', 'https://www.peekyou.com/about/contact/optout/', 'easy', '5 minutes', false, false, true, '1. Search for your profile on PeekYou\n2. Copy the unique ID from your profile URL\n3. Visit the opt-out page\n4. Paste the ID and provide your email\n5. Confirm via email link', 'high', true),
  ('usa-people-search', 'USA-People-Search', 'https://www.usa-people-search.com', 'https://www.usa-people-search.com/manage', 'easy', '5 minutes', false, false, true, '1. Search for yourself on USA-People-Search\n2. Click on your profile\n3. Click "Remove This Record" at the bottom\n4. Enter your email and complete CAPTCHA\n5. Confirm removal via email', 'high', true),
  ('zabasearch', 'ZabaSearch', 'https://www.zabasearch.com', 'https://www.intelius.com/opt-out', 'medium', '10 minutes', true, false, true, '1. ZabaSearch is owned by Intelius — use the Intelius opt-out\n2. Search for yourself on ZabaSearch first to confirm listing\n3. Visit the Intelius opt-out page\n4. Submit ID verification\n5. Allow 7-14 days for removal', 'high', true),
  ('411', '411.info', 'https://www.411.info', 'https://www.411.info/manage/optout', 'easy', '5 minutes', false, false, true, '1. Search for yourself on 411.info\n2. Locate your listing\n3. Click "Remove" or visit the opt-out form\n4. Enter the URL of your listing and your email\n5. Confirm removal via email link', 'high', true),
  ('yellowpages', 'YellowPages', 'https://www.yellowpages.com', 'https://www.yellowpages.com/about/our-policies/privacy-policy', 'medium', '10 minutes', false, true, false, '1. Email privacy@yellowpages.com\n2. Subject: "Opt-Out Request"\n3. Include name, address, phone number to remove\n4. Reference YellowPages privacy policy section on data removal\n5. Allow 30 days for processing', 'normal', true),
  ('publicrecordsnow', 'PublicRecordsNow', 'https://www.publicrecordsnow.com', 'https://www.publicrecordsnow.com/optout/', 'easy', '5 minutes', false, false, true, '1. Visit the opt-out page\n2. Enter your first name, last name, and state\n3. Locate your record\n4. Click "Remove This Record"\n5. Confirm via email', 'normal', true),
  ('clustrmaps', 'ClustrMaps', 'https://clustrmaps.com', 'https://clustrmaps.com/bl/opt-out', 'easy', '5 minutes', false, false, true, '1. Search for your name on ClustrMaps\n2. Find your profile URL\n3. Visit the opt-out form\n4. Paste your profile URL and email\n5. Confirm via email link', 'high', true),
  ('addresses', 'Addresses.com', 'https://www.addresses.com', 'https://www.intelius.com/opt-out', 'medium', '10 minutes', true, false, true, '1. Addresses.com is owned by Intelius\n2. Use the Intelius opt-out form\n3. Submit ID verification\n4. Allow 7-14 days for removal across both sites', 'normal', true),
  ('peoplebyname', 'PeopleByName', 'https://www.peoplebyname.com', 'https://www.peoplebyname.com/optout.php', 'easy', '5 minutes', false, false, false, '1. Visit the PeopleByName opt-out page\n2. Enter the URL of your listing\n3. Provide your email address\n4. Submit the form\n5. Allow 7 days for removal', 'normal', true),
  ('smartbackgroundchecks', 'SmartBackgroundChecks', 'https://www.smartbackgroundchecks.com', 'https://www.smartbackgroundchecks.com/optout', 'easy', '5 minutes', false, false, true, '1. Search for yourself on SmartBackgroundChecks\n2. Copy your profile URL\n3. Visit the opt-out page\n4. Paste URL and enter email\n5. Confirm via email', 'high', true),
  ('checkpeople', 'CheckPeople', 'https://www.checkpeople.com', 'https://www.checkpeople.com/opt-out', 'medium', '10 minutes', false, false, true, '1. Visit the CheckPeople opt-out page\n2. Search for your record\n3. Click "Remove This Listing"\n4. Verify via email\n5. Allow 7-10 days for removal', 'high', true),
  ('infotracer', 'InfoTracer', 'https://infotracer.com', 'https://infotracer.com/optout/', 'medium', '10 minutes', true, false, true, '1. Visit the InfoTracer opt-out page\n2. Search for your record by name\n3. Click "Remove" on your profile\n4. Verify identity (may require ID upload)\n5. Allow 7-14 days for removal', 'high', true),
  ('publicrecords360', 'PublicRecords360', 'https://www.publicrecords360.com', 'https://www.publicrecords360.com/optout.html', 'easy', '5 minutes', false, false, false, '1. Visit the opt-out page\n2. Provide URL of your listing\n3. Enter your email\n4. Submit and wait for confirmation\n5. Allow 7 days for removal', 'normal', true),
  ('rocketreach', 'RocketReach', 'https://rocketreach.co', 'https://rocketreach.co/optout', 'medium', '10 minutes', false, false, true, '1. Visit the RocketReach opt-out page\n2. Search for your professional profile\n3. Click "Claim and remove"\n4. Verify via business email\n5. Removal typically within 5 days', 'high', true),
  ('apollo', 'Apollo.io', 'https://www.apollo.io', 'https://www.apollo.io/privacy-policy', 'medium', '10 minutes', false, false, false, '1. Email privacy@apollo.io\n2. Subject: "Data Subject Request - Deletion"\n3. Include your full name, work email, and LinkedIn URL\n4. Request deletion under CCPA/GDPR\n5. Allow 30 days for processing', 'high', true),
  ('zoominfo', 'ZoomInfo', 'https://www.zoominfo.com', 'https://www.zoominfo.com/about-zoominfo/privacy-center', 'medium', '10 minutes', false, false, true, '1. Visit the ZoomInfo Privacy Center\n2. Click "Do Not Sell My Personal Information"\n3. Fill out the opt-out form with your email and details\n4. Verify via email link\n5. Allow 30 days for full removal', 'high', true),
  ('lead411', 'Lead411', 'https://www.lead411.com', 'https://www.lead411.com/privacy-policy/', 'medium', '10 minutes', false, false, false, '1. Email support@lead411.com\n2. Subject: "Opt-Out / Data Deletion Request"\n3. Include name, email, and any company info to remove\n4. Reference CCPA/GDPR rights\n5. Allow 14-30 days for removal', 'normal', true),
  ('peoplesearchnow', 'PeopleSearchNow', 'https://www.peoplesearchnow.com', 'https://www.peoplesearchnow.com/optout', 'easy', '5 minutes', false, false, true, '1. Search for yourself on PeopleSearchNow\n2. Find your listing\n3. Click "Remove" link\n4. Provide email and complete CAPTCHA\n5. Confirm via email', 'normal', true),
  ('advancedbackgroundchecks', 'AdvancedBackgroundChecks', 'https://www.advancedbackgroundchecks.com', 'https://www.advancedbackgroundchecks.com/removal', 'easy', '5 minutes', false, false, true, '1. Visit the AdvancedBackgroundChecks removal page\n2. Search for yourself\n3. Click your record\n4. Submit removal request with email\n5. Confirm via email link', 'high', true),
  ('idtrue', 'IDTrue', 'https://www.idtrue.com', 'https://www.idtrue.com/optout', 'easy', '5 minutes', false, false, true, '1. Search for your record on IDTrue\n2. Find your listing URL\n3. Visit the opt-out page\n4. Paste the URL and submit your email\n5. Confirm via email', 'normal', true),
  ('xlek', 'Xlek', 'https://www.xlek.com', 'https://www.xlek.com/optout', 'easy', '5 minutes', false, false, false, '1. Visit Xlek opt-out page\n2. Enter your name and state\n3. Locate your record\n4. Submit removal request\n5. Allow 7 days for processing', 'normal', true),
  ('persopo', 'Persopo', 'https://persopo.com', 'https://persopo.com/optout', 'easy', '5 minutes', false, false, true, '1. Visit Persopo opt-out page\n2. Search for your name\n3. Click "Remove This Record"\n4. Provide email and confirm CAPTCHA\n5. Verify via email link', 'normal', true)
ON CONFLICT (slug) DO NOTHING;
